var namespace_communication_1_1_model_binders_1_1_attributes =
[
    [ "FromSwagDtoAttribute", "class_communication_1_1_model_binders_1_1_attributes_1_1_from_swag_dto_attribute.html", "class_communication_1_1_model_binders_1_1_attributes_1_1_from_swag_dto_attribute" ],
    [ "IFromSwagDtoAttribute", "interface_communication_1_1_model_binders_1_1_attributes_1_1_i_from_swag_dto_attribute.html", "interface_communication_1_1_model_binders_1_1_attributes_1_1_i_from_swag_dto_attribute" ]
];